federation_version: =2.0.0
subgraphs:
  graph-1-nodejs:
    routing_url: http://dummy/
    schema:
      file: ./generated/graph-1-nodejs.graphql
  graph-2-dgraph:
    routing_url: http://dummy/
    schema:
      file: ./generated/graph-2-dgraph.graphql
